/**
 * Interactive Demo Tour Component
 * 5-step guided walkthrough for hackathon judging, executive pitches, and user onboarding.
 */
import { store } from "../store.js";

const TOUR_STEPS = [
  {
    title: "1. Multi-Agent Screenplay Triage",
    desc: "ClearFrame reads raw .pdf/.txt screenplays and orchestrates multiple AI agents to parse real page numbers, extract brands, music, real entities, and run sourced deep research across the web.",
    action: () => store.setState({ view: "workspace" })
  },
  {
    title: "2. Deterministic Legal Arithmetic (No LLM Guessing)",
    desc: "Copyright terms and public domain dates are calculated deterministically via Python statutory arithmetic (Title 17 & MMA), NOT generated by an LLM. Music specifically receives two independent evaluations for Composition vs Sound Recording.",
    action: () => {
      store.setState({ view: "workspace" });
      const musicItem = store.state.currentReport?.items.find(i => i.category === "MUSIC");
      if (musicItem) store.selectItem(musicItem.item_id);
    }
  },
  {
    title: "3. Sourced Citations & Validation Guardrails",
    desc: "Every claim carries verifiable inline citations [ev_...] linked to retrieved registry records. Uncited statements and subjective legal conclusions are automatically stripped during validation.",
    action: () => {
      store.setState({ view: "workspace" });
      const cokeItem = store.state.currentReport?.items.find(i => i.mention_text === "COCA-COLA");
      if (cokeItem) store.selectItem(cokeItem.item_id);
    }
  },
  {
    title: "4. The Review Gate (Strict Human-in-the-Loop)",
    desc: "The system strictly refuses to export while any item remains unreviewed. A clearance log cannot leave the building without an attorney confirming, rejecting, or escalating every item.",
    action: () => {
      store.export();
    }
  },
  {
    title: "5. Production-Ready Signed-Off Clearance Log",
    desc: "Once 100% of items are decided by qualified counsel, the report is marked SIGNED_OFF and exported as a standardized legal markdown binder complete with source dates and statutory citations.",
    action: () => {
      store.setState({ gateModalOpen: false, view: "workspace" });
    }
  }
];

export function initDemoTour() {
  let currentStepIndex = 0;

  window.addEventListener("start-demo-tour", () => {
    if (!store.state.currentReport) {
      store.loadDemoReport();
    }
    currentStepIndex = 0;
    renderTourStep();
  });

  function renderTourStep() {
    let overlay = document.getElementById("tourOverlay");
    if (!overlay) {
      overlay = document.createElement("div");
      overlay.id = "tourOverlay";
      overlay.className = "fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm";
      document.body.appendChild(overlay);
    }

    const step = TOUR_STEPS[currentStepIndex];
    if (step.action) step.action();

    overlay.innerHTML = `
      <div class="bg-gray-800 border border-blue-500/30 rounded-2xl max-w-lg w-full p-8 shadow-2xl relative animate-fade-in">
        <div class="flex items-center justify-between mb-4">
          <span class="text-xs font-mono font-bold uppercase tracking-wider text-blue-400">
            Guided Tour · Step ${currentStepIndex + 1} of ${TOUR_STEPS.length}
          </span>
          <button id="closeTourBtn" class="text-gray-400 hover:text-white transition-colors">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
          </button>
        </div>

        <h3 class="text-xl font-bold text-white tracking-tight mb-3">${step.title}</h3>
        <p class="text-sm text-gray-300 leading-relaxed mb-8">${step.desc}</p>

        <div class="flex items-center justify-between pt-4 border-t border-gray-700/60">
          <button id="prevTourBtn" ${currentStepIndex === 0 ? "disabled" : ""} 
            class="px-4 py-2 rounded-xl border border-gray-600 bg-gray-700 text-gray-300 text-sm font-semibold disabled:opacity-30 transition-all">
            Previous
          </button>

          <div class="flex items-center gap-2">
            ${TOUR_STEPS.map((_, i) => `<span class="w-2.5 h-2.5 rounded-full ${i === currentStepIndex ? "bg-blue-500" : "bg-gray-700"}"></span>`).join("")}
          </div>

          <button id="nextTourBtn" class="px-5 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-sm font-semibold shadow-md shadow-blue-600/25 transition-all">
            ${currentStepIndex === TOUR_STEPS.length - 1 ? "Finish Tour" : "Next Step"}
          </button>
        </div>
      </div>
    `;

    overlay.querySelector("#closeTourBtn").onclick = () => overlay.remove();
    const prevBtn = overlay.querySelector("#prevTourBtn");
    if (prevBtn) {
      prevBtn.onclick = () => {
        if (currentStepIndex > 0) {
          currentStepIndex--;
          renderTourStep();
        }
      };
    }
    const nextBtn = overlay.querySelector("#nextTourBtn");
    if (nextBtn) {
      nextBtn.onclick = () => {
        if (currentStepIndex < TOUR_STEPS.length - 1) {
          currentStepIndex++;
          renderTourStep();
        } else {
          overlay.remove();
        }
      };
    }
  }
}
